name: Terraform plan

on:
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Terraform init
        uses: docker://hashicorp/terraform:0.13.3
        with:
          entrypoint: terraform
          args: init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run Terraform validate
        uses: docker://hashicorp/terraform:0.13.3
        with:
          entrypoint: terraform
          args: validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run Terraform plan
        uses: docker://hashicorp/terraform:0.13.3
        id: plan
        with:
          entrypoint: terraform
          args: plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env: 
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} 